packages:
  - packages/*
  - libs/*
  - apps/*
patchedDependencies:
  electron-vite: patches/electron-vite.patch
catalog:
  '@tg-search/eslint-config': ^1.0.1
  '@tg-search/logg': ^1.0.0-beta.18
  '@tg-search/result': ^1.0.0-beta.18
  '@xsai-ext/providers-cloud': ^0.3.1
  '@xsai-ext/providers-local': ^0.3.1
  '@xsai/embed': ^0.3.1
onlyBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - bufferutil
  - electron
  - es5-ext
  - esbuild
  - sharp
  - unrs-resolver
  - utf-8-validate
  - vue-demi
  - websocket
